consul - 3.7.1

diff --git a/consul/rendered.yaml b/consul/rendered.yaml
--- a/consul/rendered.yaml
+++ b/consul/rendered.yaml
@@ -25,7 +25,7 @@ metadata:
 ---
 apiVersion: v1
 data:
-  gossip-key: Q3dKT2IyeTNHMFdmOFpSRENtTmtLVXE5
+  gossip-key: eWU4eHpQdnRLYmFXWEFZem5lQ1g4Rkg1
 kind: Secret
 metadata:
   labels:
@@ -104,7 +104,7 @@ spec:
   template:
     metadata:
       labels:
-        chart: consul-3.7.1
+        chart: consul-3.8.0
         component: consul-consul
         heritage: Tiller
         release: consul
@@ -126,43 +126,7 @@ spec:
       - command:
         - /bin/sh
         - -ec
-        - |
-          IP=$(hostname -i)
-          if [ -e /etc/consul/secrets/gossip-key ]; then
-            echo "{\"encrypt\": \"$(base64 /etc/consul/secrets/gossip-key)\"}" > /etc/consul/encrypt.json
-            GOSSIP_KEY="-config-file /etc/consul/encrypt.json"
-          fi
-
-          for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
-              while true; do
-                  echo "Waiting for ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME} to come up"
-                  ping -W 1 -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc > /dev/null && break
-                  sleep 1s
-              done
-          done
-
-          PEERS=""
-          for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
-            NEXT_PEER="$(ping -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc | awk -F'[()]' '/PING/{print $2}')"
-            if [ "${NEXT_PEER}" != "${POD_IP}" ]; then
-              PEERS="${PEERS}${PEERS:+ } -retry-join ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc"
-            fi
-          done
-
-          exec /bin/consul agent \
-            -ui \
-            -domain=consul \
-            -data-dir=/var/lib/consul \
-            -server \
-            -bootstrap-expect=${INITIAL_CLUSTER_SIZE} \
-            -disable-keyring-file \
-            -bind=0.0.0.0 \
-            -advertise=${IP} \
-            ${PEERS} \
-            ${GOSSIP_KEY} \
-            -client=0.0.0.0 \
-            -dns-port=${DNSPORT} \
-            -http-port=8500
+        - "set -o pipefail\n\nif [ -z \"$POD_IP\"  ]; then\n  POD_IP=$(hostname -i)\nfi\nFQDN_SUFFIX=\"${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc\"\nNODE_NAME=\"$(hostname -s).${FQDN_SUFFIX}\"\nif [ -e /etc/consul/secrets/gossip-key ]; then\n  echo \"{\\\"encrypt\\\": \\\"$(base64 /etc/consul/secrets/gossip-key)\\\"}\" > /etc/consul/encrypt.json\n  GOSSIP_KEY=\"-config-file /etc/consul/encrypt.json\"\nfi\n\nJOIN_PEERS=\"\"\nJOIN_PEERS=\"\"\nfor i in $( seq 0 $((${INITIAL_CLUSTER_SIZE} - 1)) ); do\n  JOIN_PEERS=\"${JOIN_PEERS}${JOIN_PEERS:+ }${STATEFULSET_NAME}-${i}.${FQDN_SUFFIX}\"\ndone\n\nJOIN_PEERS=$( printf \"%s\\n\" $JOIN_PEERS | sort | uniq )\n\n# Require multiple loops in the case of unstable DNS resolution\nSUCCESS_LOOPS=5\nwhile [ \"$SUCCESS_LOOPS\" -gt 0 ]; do\n  ALL_READY=true\n  JOIN_LAN=\"\"\n  for THIS_PEER in $JOIN_PEERS; do\n      # Make sure we can resolve hostname and ping IP\n      if PEER_IP=\"$(ping -c 1 $THIS_PEER | awk -F'[()]' '/PING/{print $2}')\" && [ \"$PEER_IP\" != \"\" ]; then \n        if [ \"${PEER_IP}\" != \"${POD_IP}\" ]; then\n          JOIN_LAN=\"${JOIN_LAN}${JOIN_LAN:+ } -retry-join=$THIS_PEER\"\n        fi\n      else\n        ALL_READY=false\n        break\n      fi\n  done\n  if $ALL_READY; then\n    SUCCESS_LOOPS=$(( SUCCESS_LOOPS - 1 ))\n    echo \"LAN peers appear ready, $SUCCESS_LOOPS verifications left\"\n  else\n    echo \"Waiting for LAN peer $THIS_PEER...\"\n  fi\n  sleep 1s\ndone\n\n\nWAN_PEERS=\"\"\n\nJOIN_WAN=\"\"\nSUCCESS_LOOPS=5\nwhile [ \"$WAN_PEERS\" != \"\" ] && [ \"$SUCCESS_LOOPS\" -gt 0 ]; do\n  ALL_READY=true\n  JOIN_WAN=\"\"\n  for THIS_PEER in $WAN_PEERS; do\n      # We don't care if we can ping the peer, but we do care that we can get its IP\n      if PEER_IP=\"$( ( ping -c 1 $THIS_PEER || true ) | awk -F'[()]' '/PING/{print $2}')\" && [ \"$PEER_IP\" != \"\" ]; then \n        if [ \"${PEER_IP}\" != \"${POD_IP}\" ]; then\n          JOIN_WAN=\"${JOIN_WAN}${JOIN_WAN:+ } -retry-join-wan=$THIS_PEER\"\n        fi\n      else\n        ALL_READY=false\n        break\n      fi\n  done\n  if $ALL_READY; then\n    SUCCESS_LOOPS=$(( SUCCESS_LOOPS - 1 ))\n    echo \"WAN peers appear ready, $SUCCESS_LOOPS verifications left\"\n  else\n    echo \"Waiting for WAN peer $THIS_PEER...\"\n  fi\n  sleep 1s\ndone\n\nexec /bin/consul agent \\\n  -ui \\\n  -domain=consul \\\n  -data-dir=/var/lib/consul \\\n  -server \\\n  -bootstrap-expect=$( echo \"$JOIN_PEERS\" | wc -w ) \\\n  -disable-keyring-file \\\n  -bind=0.0.0.0 \\\n  -advertise=${POD_IP} \\\n  ${JOIN_LAN} \\\n  ${JOIN_WAN} \\\n  ${GOSSIP_KEY} \\\n  -client=0.0.0.0 \\\n  -dns-port=${DNSPORT} \\\n  -http-port=8500\n"
         env:
         - name: INITIAL_CLUSTER_SIZE
           value: "3"
@@ -178,7 +142,7 @@ spec:
               fieldPath: metadata.namespace
         - name: DNSPORT
           value: "8600"
-        image: consul:1.5.2
+        image: consul:1.5.3
         imagePullPolicy: Always
         livenessProbe:
           exec:
@@ -256,7 +220,7 @@ kind: Pod
 metadata:
   annotations:
     helm.sh/hook: test-success
-  name: consul-ui-test-23h90
+  name: consul-ui-test-hwa1x
 spec:
   containers:
   - command:
